/** Story panel bodies — dynamically imported so the first JS chunk stays light. */
export const BODIES: Record<string, string> = {
  "title": "The Common Task is humanity's shared duty: to overcome death, restore life to all who have died, and bring nature under intelligent and moral dominion so that life may continue without limit.\n\nIts principles are ancient, but they were revived in modern form by Nikolai Fyodorov, the Russian Orthodox philosopher whose ideas helped give rise to Cosmism. At the heart of the Common Task are several convictions: that life, intelligence, and progress everlasting are the highest good; that death should not be accepted as final; that the living bear a responsibility to the dead and the unborn; and that science, religion, and moral duty are not separate callings, but parts of the same labor.\n\nThese principles form the foundation of everything Hyrum does today. The Common Task is his life's mission, not as metaphor or abstraction, but as real work set before him, and ultimately before all humanity.",
  "cosmism": "Hyrum is working to restore Cosmism: bringing its ideas into the present day and developing them into a practical mission for humanity's survival, flourishing, and long-term future.\n\nCosmism is a philosophical tradition centered on radical scientific progress, the expansion of life and intelligence beyond Earth, and the eventual overcoming of death and biological limitation. Its purpose is not simply to imagine a better future, but to organize human effort toward building one.\n\nIt is not a replacement for religion, but a practical extension of it: a call to build Heaven on Earth through moral responsibility, scientific progress, and coordinated human action.\n\nFor Hyrum, Cosmism is humanity's light in the darkness. Without it, humanity's best fate is Hell. Its worst is that there is no Hell, no Heaven, and no one waiting beyond death at all, only the final disappearance of life, memory, and intelligence into entropy.",
  "christianity": "Hyrum was raised in a Bible-believing Christian home where scripture, prayer, family worship, and service were part of daily life. His faith in Jesus Christ deepened during his two-year mission and continues to shape his view of responsibility, work, and human dignity. Christianity is the moral foundation beneath his interest in science, technology, and the long-term future of mankind.",
  "church": "Hyrum was born into The Church of Jesus Christ of Latter-day Saints, the Kingdom of Heaven on earth today. His faith informs his belief that building, healing, learning, and preserving life are not separate from discipleship, but part of it.",
  "noah": "Noah Cryotechnology advances whole-organism cryopreservation, pausing entire living systems to protect life on Earth and carry it toward the stars. Hyrum left Pennsylvania and moved to Texas as the first hire, helping build the first lab, raise millions from Valyrian, Prelude, and Zee Prime Capital, and launch Noah's first public facing product, Cryopets.",
  "cryopets": "CryoPets is Noah's cryosleep service for companion animals, preserving pets after clinical death so that future medicine may one day restore them.\n\nAs Head of Growth at Noah, Hyrum led the launch of CryoPets and helped grow its waitlist to more than 10,000 pets across the United States, making it the largest rollout of a cryosleep service in history.",
  "hydradao": "Hyrum co-built HydraDAO's fundraising and media efforts. HydraDAO is a nonprofit funding frontier science focused on whole-body replacement, cloned and synthetic embryos, progressive brain tissue replacement, organ replacement, bodyoids, and other engineering-heavy approaches to biological repair. The organization has raised over $4M to support high-risk research that traditional institutions are often too slow or conservative to fund.",
  "dowellbio": "Dowell Bio is a solely HydraDAO-funded research effort focused on spinal cord transection and refusion. The project has already successfully severed and rejoined spinal cords in animal models, with ongoing work aimed at measuring functional recovery and advancing the technique toward clinical use.\n\nIn 2025, the team performed more than 200 rat surgeries with rehabilitation and video tracking, developed a roadmap toward human trials, and began analyzing microscopy and clinical data for patents and research papers. Early pig trials are now underway, moving the research into larger translational models and already showing promising initial results.",
  "cryodao": "Hyrum joined CryoDAO in late 2024 to manage growth. CryoDAO is a nonprofit organization funding cryopreservation research across organ preservation, whole-body preservation, and revival-relevant biology. It has backed research including sheep ovary vitrification and transplantation, whole non-hibernating mammal high-subzero preservation and revival, and additional projects across the biostasis field. To date, CryoDAO has raised over $5M for cryopreservation research.",
  "cryorat": "CryoRat is CryoDAO's whole-body rat preservation program. The program focuses on high-subzero cryoprotection as a staged path toward eventual whole-body mammalian revival. Hyrum co-launched and helped prepare the fundraiser, which closed at $900K in less than a day. The project includes perfusion optimization, cryoprotectant mapping across organs and brain tissue, viability testing, in-house micro-CT, and staged revival attempts as milestones are reached.",
  "mta": "Hyrum serves as Head of Growth at the Mormon Transhumanist Association, a nonprofit dedicated to advancing abundant human flourishing through the compassionate use of science and technology. Founded in 2006, the Association explores the intersection of religion, science, and technological progress, encouraging today's pioneers to pursue new frontiers with the conviction of their faith. Today, it is the largest transhumanist association in the world.",
  "wwe": "Hyrum co-founded Worlds Without End, a frontier VC fund investing $250K to $500K in pre-seed and seed startups focused on accelerating development in frontier radical life extension, space travel, and artificial intelligence.",
  "mission": "Hyrum submitted his papers and left to serve a two-year mission for The Church of Jesus Christ of Latter-day Saints in the late spring of 2022. He was called to the Utah Salt Lake City Mission, where his assigned areas included Holladay, Murray, and Cottonwood Heights. At times, he served across areas covering up to 20 congregations. His mission developed his love for religion, philosophy, church history, apologetics, public speaking, and direct outreach.",
  "byu": "After graduating high school early, Hyrum attended a single semester at BYU as a declared Mechanical Engineering major before leaving to serve a two-year mission for his church. During this time, he became disillusioned with the conventional academic path. College, he concluded, is an overpriced scam mostly filled with the blind leading the blind; new serious builders tend not to be there anymore, but instead building, and learning as they build.",
  "freemasonry": "Hyrum's interest in esoteric knowledge, moral formation, fraternity, and self-improvement eventually led him to Freemasonry. He received his third degree at the age of 20, becoming a Master Mason. While not central to his professional work, Freemasonry reflects his broader interest in disciplined self-development, inherited tradition, symbolism, and moral architecture.",
  "moroni": "Captain Moroni is a military leader from the Book of Mormon. During a time of war and division, he tore his coat and wrote upon it:\n\n“In memory of our God, our religion, and freedom, and our peace, our wives, and our children.”\n\nHe fastened the torn cloth to a pole, creating a banner he called the Title of Liberty, and raised it as a symbol of what was worth defending.\n\nFor Hyrum, the Title of Liberty serves as a compass, representing faith, freedom, peace, family, and the future.\n\nThat image inspired this website. The constellation you have now clicked through depicts Captain Moroni holding the Title of Liberty."
};
